module.exports = {
    "110": "Restart marker reply.",
    "120": "Service ready in nn minutes.",
    "125": "Data Connection already open; transfer starting.",
    "150": "File status okay; about to open data connection.",
    "200": "Command okay.",
    "202": "Command not implemented, superfluous at this site.",
    "211": "System status, or system help reply.",
    "212": "Directory status.",
    "213": "File status.",
    "214": "Help message.",
    "215": "NAME system type.",
    "220": "Service ready for new user.",
    "221": "Service closing control connection.",
    "225": "Data connection open; no transfer in progress.",
    "226": "Closing data connection.",
    "227": "Entering Passive Mode.",
    "230": "User logged in, proceed. This status code appears after the client sends the correct password. It indicates that the user has successfully logged on.",
    "250": "Requested file action okay, completed.",
    "257": "'\"'PATHNAME'\"' created.",
    "331": "User name okay, need password.",
    "332": "Need account for login.",
    "350": "Requested file action pending further information.",
    "421": "Error 421 Service not available, closing control connection.\n            Error 421 User limit reached\n            Error 421 You are not authorized to make the connection\n            Error 421 Max connections reached\n            Error 421 Max connections exceeded",
    "425": "Cannot open data connection.",
    "426": "Connection closed; transfer aborted.",
    "450": "Requested file action not taken.",
    "451": "Requested action aborted: local error in processing.",
    "452": "Requested action not taken. Insufficient storage space in system.",
    "500": "Syntax error, command unrecognized, command line too long.",
    "501": "Syntax error in parameters or arguments.",
    "502": "Command not implemented.",
    "503": "Bad sequence of commands.",
    "504": "Command not implemented for that parameter.",
    "530": "User not logged in.",
    "532": "Need account for storing files.",
    "550": "Requested action not taken. File unavailable, not found, not accessible",
    "552": "Requested file action aborted. Exceeded storage allocation.",
    "553": "Requested action not taken. File name not allowed.",
    "10054": "Connection reset by peer. The connection was forcibly closed by the remote host.",
    "10060": "Cannot connect to remote server.",
    "10061": "Cannot connect to remote server. The connection is actively refused by the server.",
    "10066": "Directory not empty.",
    "10068": "Too many users, server is full."
};